name: Comment Hello on Command

on:
  issue_comment:
    types: [created]

jobs:
  comment_hello:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check if comment contains /comment-it``
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment.body;
            const trigger = '/comment-it';
            if (comment.includes(trigger)) {
              console.log('Command found in comment!');
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '👋 Thanks for reporting!'
              })
            } else {
              console.log('Command not found in comment.');
            }
